### PR TITLE
Make clustering of annotations more flexible

### PR DESCRIPTION
**Pull request by tarbrain**
Hello Claus,

I have made some very handy changes to the clusterer:

- added `NSMutableSet allAnnotations` to collect all annotations - not only those which are visible
- added `NSMutableSet excludedAnnotations` for annotations which should not be clustered
- removed annotation deselection code when zooming

Have a look and tell me what you think.

Cheers
tarbrain

### CODE REVIEW

**Comment by choefele** [comment]
How is `allAnnotations` different to the existing property `annotations`? `annotations` already contains all annotations. There was a bug in previous releases, but this is now fixed.

If you want to exclude annotations for clustering, just don't add them to the clustering.

As for annotation deselection code: can you please comment in #65 on what you did and how you propose to solve the issue. I prefer a PR that addresses one issue instead of multiples.

Thanks

**Comment by tarbrain** [comment]
- `allAnnotations`:

I remember I have implemented the feature and you integrated it into the codebase according to this issue: https://github.com/choefele/CCHMapClusterController/issues/62#issuecomment-67617906

- excluding annotations:

I have tried by adding annotations directly to the `MKMapView` but it seems that `MKMapView` will not properly respond to the ViewController since most of the delegate methods are intercepted by the cluster controller.

- deselection on zoom

I have just removed the deselection code. By adding the selected annotation to the  `excludedAnnotations` set by the application the annotations will stay selected.

**Comment by choefele** [comment]
Excluding annotations: the cluster controller won't touch annotations that aren't `CCHMapClusterAnnotation`s. There's a [unit test for this](https://github.com/choefele/CCHMapClusterController/blob/master/CCHMapClusterController%20Tests/CCHMapClusterControllerTests.m#L227)

Deselection on zoom: please provide a separate pull request.

Thanks

**Comment by tarbrain** [comment]
Well, I have added the exclusion set to keep annotations on the map. Otherwise - if you would want to exclude the annotations temporarily you would have to remove and re-add them to the map which can cause flickering and messes too much with the selected / deselected state of the annotations.

**Comment by beribas** [comment]
My use case is to set maxZoomLevelForClustering and I would expect in the not-clustered-state that the selection is preserved. Is there a reason to deselect annotations in the not clustered zoom level? If not, this code in mapView:regionDidChangeAnimated: would just do fine:
```
    if (hasZoomed && self.zoomLevel < self.maxZoomLevelForClustering) {
        [self deselectAllAnnotations];
    }
```

**Pull request closed without merging**
