### PR TITLE
Add delegates for adding/removing annotations to the map

### PR DESCRIPTION
**Pull request by mikrobi**
In my project I need to know when new annotations are added to or removed from the map.

### CODE REVIEW

**Comment by choefele** [comment]
Hi Jakob,

Can you tell me a bit more what you need the delegate methods for? Would `MKMapViewDelegate`'s `mapView:didAddAnnotationViews:` be sufficient?

Thanks,
Claus

**Comment by mikrobi** [comment]
Hmm, `mapView:didAddAnnotationViews:`doesn't really as this method is only called, when the view of the annotation is actually added because we are about to scroll into the visible area of that annotation.

In my app I have a combination of overlays and annotations. For some annotations I also have to add an overlay (or remove the overlay when the associated annotation is removed from the map). The overlays are way bigger than the annotations, so the map view needs to be aware of them even before the annotation view is being added. Right now there is no way to get informed when the cluster controller adds or removes annotations.

**Comment by choefele** [comment]
One more question: if you enable `marginFactor` (by default it's 0.5), `CCHMapClusterController` will automatically cluster annotations beyond the visible area and add those annotations to the map. For this reason, I would expect `mapView:didAddAnnotationViews:` to be called for the annotations outside the visible area as well. I think this would solve your problem.

Can you please check if `mapView:didAddAnnotationViews:` is called for the annotations that are included in the margin?

Thanks,
Claus

**Comment by mikrobi** [comment]
The `marginFactor` doesn't really help for my issue: Even when we would add all annotation directly to the `MKMapView` we would not get the `mapView:didAddAnnotationViews:` call back immediately. Only when we scroll there and `MKMapView` thinks it should start rendering the annotation. As we are working with overlays, that a way bigger than than the annotations, we want to add the overlays right after adding the annotation (not its view) to the `MKMapView`.

**Comment by choefele** [comment]
I think `mapView:didAddAnnotationViews:` is called at the right time. To check:
- Change the [initial zoom region](https://github.com/choefele/CCHMapClusterController/blob/37fbf361788ac655f438800db8941b05f577eb8e/CCHMapClusterController%20Example%20iOS/CCHMapClusterController%20Example%20iOS/MapViewController.m#L118) of the example to `MKCoordinateRegionMakeWithDistance(location, 25000, 25000)`
- Implement `didAddAnnotationViews` by adding `- (void)mapView:(MKMapView *)mapView didAddAnnotationViews:(NSArray *)views { NSLog(@"didAddAnnotationViews"); }` to `MapViewController`

This will start the app with most annotations in the visible area, but some inside the margin. When starting the app, you will see the log messages. Wait until all annotations are loaded. 

When you pan the map, you'll find that annotations from inside the margin will appear in the visible area, but there's no log message. That means `mapView:didAddAnnotationViews:` is called for annotations in the margin thus you can add you overlay in this delegate.

**Comment by choefele** [comment]
Closing this for now. Please reopen if still needed. Thanks

**Pull request closed without merging**
